name: portfolio

services:
  portfolio-app:
    container_name: portfolio-app
    image: ${PORTFOLIO_IMAGE}:${BUILD_VERSION_NO}
    env_file:
      - .env
    ports:
      - ${PORTFOLIO_PORT_BINDING}
    restart: always
