version: "3.8"
services:
  react-web:
    image: ${DOCKER_REACT_WEB_REGISTRY}:${BUILD_VERSION_NO}
    container_name: ${DOCKER_REACT_WEB_CONTAINER_NAME}
    ports:
      - ${DOCKER_REACT_WEB_PORT_BINDING}
    stdin_open: true
    tty: true