export const envConfig = {
  NODE_ENV: process.env.REACT_APP_ENV!,
  VERSION_NO: process.env.REACT_APP_BUILD_VERSION_NO,
  PORTFOLIO_API_BASE_URL: process.env.REACT_APP_PORTFOLIO_API_BASE_URL,
  STATIC_FILE_BASE_URL: process.env.REACT_APP_STATIC_FILE_BASE_URL,
  GITHUB_RELEASE_URL: process.env.REACT_APP_GITHUB_RELEASE_URL,
  GA4_ID: process.env.REACT_APP_GA_MEASUREMENT_ID,
  SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
}
